### ISSUE TITLE
Pulling ESB File

### ISSUE THREAD

**Issue by pjmm1** [badger707/esb-smart-meter-reading-automation#4]
Hi
I am trying to use your script to download my ESB readings
I have created a file and placed your script in with the MPRN User Name Password changed
I have Phyton 3 Running
Do I have to have your script in a particular Named Directory
Your program references from bs4 import BeautifulSoup what is this referring to.
Do you have an example .bat file that demonstrates executes your script
Many thanks

**Comment by badger707** [comment]
Hi,

You're on the right path. Because you asked for .bat file, my guess is you are on Windows machine... You can run this script in CMD from any directory.
BeautifulSoup is HTML parsing library for Python.
You run this script exactly in the same way you would run any other Python script on your Windows machine, and .bat is not needed for basic run/test.
